name: Build packages

on:
  push

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.release }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - 25.12.0-rc4
        arch:
          - aarch64_generic

    steps:
      - uses: actions/checkout@v4

      - name:
        run: mkdir artifacts feed

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feed
          PACKAGES: speedtest-go

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch}}-${{ matrix.release }}/packages
          path: artifacts/bin/packages/${{ matrix.arch }}/packages/*.apk
