name: Build packages

on:
  push

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.release }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - 25.12.0-rc4
        arch:
          - aarch64_generic

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          FEEDNAME: bluelife
          PACKAGES: smtprelay netstats2mqtt

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch}}-${{ matrix.release }}
          path: bin/packages/${{ matrix.arch }}/bluelife/*.apk
